# Numpy

## 安装numpy

In [5]:
import numpy
numpy.__version__

'2.3.5'

## Numpy的数据结构

In [6]:
l = [i for i in range(10)]
print(l)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [7]:
l[5] = 100
print(l)

[0, 1, 2, 3, 4, 100, 6, 7, 8, 9]


In [8]:
l[5] = 'learning numpy'
print(l)

[0, 1, 2, 3, 4, 'learning numpy', 6, 7, 8, 9]


In [9]:
import array
arr = array.array('i', [i for i in range(10)])
print(arr)

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [10]:
arr[5] = 100
print(arr)

array('i', [0, 1, 2, 3, 4, 100, 6, 7, 8, 9])


In [11]:
arr[5] = 'learning numpy'

TypeError: 'str' object cannot be interpreted as an integer

In [12]:
import numpy as np

arr = np.array([i for i in range(10)])
print(arr)
print(type(arr))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [13]:
arr[5] = 100
print(arr)

[  0   1   2   3   4 100   6   7   8   9]


In [14]:
arr[5] = 'learning numpy'

ValueError: invalid literal for int() with base 10: 'learning numpy'

In [15]:
print(arr.dtype)

int64


## `ndarray`的创建

In [16]:
# 创建一个长度为10的数组，数组的值都是0。
zeros = np.zeros(10)
print(zeros)
print(zeros.dtype) # 默认的数量类型是浮点型。

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
float64


In [17]:
zeros_two = np.zeros(10, dtype=int) # 创建整形数组。
print(zeros_two)
print(zeros_two.dtype)

[0 0 0 0 0 0 0 0 0 0]
int64


In [18]:
a = [1, 2, 3]
arr = np.zeros_like(a)
print(arr)

[0 0 0]


In [19]:
# 创建一个3×5的浮点型数组，数组的值都是1。
ones = np.ones(shape=(3, 5), dtype=float)
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [20]:
a = [[1, 2, 3], [4, 5, 6]]
arr = np.ones_like(a)
print(arr)

[[1 1 1]
 [1 1 1]]


## `ndarray`的类型

In [21]:
arr = np.arange(10)
print(arr)
print(arr.dtype)

[0 1 2 3 4 5 6 7 8 9]
int64


In [22]:
# 强制转换为整形
arr[5] = 3.14
print(arr)
print(arr.dtype)

[0 1 2 3 4 3 6 7 8 9]
int64


In [23]:
# 创建浮点数据类型。
arr2 = np.array([1, 2, 3.14])
print(arr2)
print(arr2.dtype)

[1.   2.   3.14]
float64


## Numpy的基本属性

In [24]:
x = np.arange(15).reshape(3, 5)
y = np.arange(10)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[0 1 2 3 4 5 6 7 8 9]


In [25]:
# 数组的维度
print(x.ndim)
print(y.ndim)

2
1


In [26]:
# 数组的形状
print(x.shape)
print(y.shape)

(3, 5)
(10,)


In [27]:
# 数组中的元素数量
print(x.size)
print(y.size)

15
10


## 数据操作

### 改变形状

In [28]:
x = np.arange(10)
print(x)
print(x.ndim)

[0 1 2 3 4 5 6 7 8 9]
1


In [29]:
w = x.reshape(2, 5)
print(w)
print(w.ndim)

[[0 1 2 3 4]
 [5 6 7 8 9]]
2


In [30]:
w = x.reshape(10, -1) # -1会根据数据数量和行数自动计算合适的列数。
print(w)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


### 数据访问

In [31]:
x = np.arange(15).reshape(3, 5)
y = np.arange(10)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[0 1 2 3 4 5 6 7 8 9]


In [32]:
# 访问一维数组
print(y)
print(y[0])
print(y[-1])

[0 1 2 3 4 5 6 7 8 9]
0
9


In [34]:
# 访问二维数组
print(x)
print(x[2, 2]) # 使用元组访问，等价于x[(2, 2)]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
12


### 数据切片

In [35]:
print(f'原数组={y}')
print(y[2:5])
print(y[:5])
print(y[5:])
print(y[::2])
print(y[::-1])

原数组=[0 1 2 3 4 5 6 7 8 9]
[2 3 4]
[0 1 2 3 4]
[5 6 7 8 9]
[0 2 4 6 8]
[9 8 7 6 5 4 3 2 1 0]


In [36]:
print(x)
print(x[:2, :3]) # 前两行前三列。
print(x[:2, ::2])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0 1 2]
 [5 6 7]]
[[0 2 4]
 [5 7 9]]


In [37]:
# 读取第一行
print(x)
print(x[0])
print(x[0, :])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[0 1 2 3 4]
[0 1 2 3 4]


In [38]:
# 读取第一列
print(x)
col = x[:, 0]
print(col)
print(col.ndim)
print(col.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[ 0  5 10]
1
(3,)


### 视图

In [39]:
sub_x = x[:2, :3]
print(x)
print(sub_x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0 1 2]
 [5 6 7]]


In [40]:
sub_x[0, 0] = 100
print(x)
print(sub_x)

[[100   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]]
[[100   1   2]
 [  5   6   7]]


In [41]:
sub_x = x[:2, :3].copy()
sub_x[0, 0] = 100
print(x)
print(sub_x)

[[100   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]]
[[100   1   2]
 [  5   6   7]]


### 数组合并

In [42]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
print(x)
print(y)
print(np.concatenate([x, y]))

[1 2 3]
[3 2 1]
[1 2 3 3 2 1]


In [43]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [44]:
print(np.concatenate([a, a]))  # 垂直方向进行拼接

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [45]:
w = np.concatenate([a, a], axis=1)
print(w) # 水平方向进行拼接


[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [46]:
w[0, 0] = 100
print(w)
print(a)

[[100   2   3   1   2   3]
 [  4   5   6   4   5   6]]
[[1 2 3]
 [4 5 6]]


## Numpy的运算

### 通用函数

In [47]:
n = 1000000
l = [i for i in range(n)]

In [48]:
%%time
double = []
for i in l:
    double.append(2 * i)
print(f"列表长度: {len(double)}")
print("前10个元素:", double[:10])

列表长度: 1000000
前10个元素: [0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
CPU times: user 28.8 ms, sys: 6.54 ms, total: 35.4 ms
Wall time: 34.8 ms


In [49]:
%%time
double = [2 * i for i in l]
print(f"列表长度: {len(double)}")
print("前10个元素:", double[:10])

列表长度: 1000000
前10个元素: [0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
CPU times: user 21.7 ms, sys: 7.87 ms, total: 29.6 ms
Wall time: 30.2 ms


In [50]:
l = np.arange(n)

In [51]:
%%time
double = np.array(2 * i for i in l)

CPU times: user 5.86 ms, sys: 2.65 ms, total: 8.51 ms
Wall time: 9.17 ms


In [52]:
%%time
double = 2 * l # Numpy支持向量与常数的运算操作
print(double[:10])

[ 0  2  4  6  8 10 12 14 16 18]
CPU times: user 1.17 ms, sys: 1.93 ms, total: 3.11 ms
Wall time: 2.22 ms


In [53]:
x = np.arange(1, 16).reshape(3, 5)

print(x)
print(x + 1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 2  3  4  5  6]
 [ 7  8  9 10 11]
 [12 13 14 15 16]]


In [54]:
print(x)
print(np.sin(x))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
 [-0.2794155   0.6569866   0.98935825  0.41211849 -0.54402111]
 [-0.99999021 -0.53657292  0.42016704  0.99060736  0.65028784]]


### 广播机制

In [74]:
a = np.ones((3, 4))
b = np.ones((3, 5))

print(a)
print(b)

print(a + b)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


ValueError: operands could not be broadcast together with shapes (3,4) (3,5) 

### 矩阵运算

In [76]:
a = np.arange(4).reshape(2, 2)
b = np.full((2, 2), 10)
print(a)
print(b)
print(a + b)

[[0 1]
 [2 3]]
[[10 10]
 [10 10]]
[[10 11]
 [12 13]]


In [77]:
print(a)
print(b)
print(a.dot(b)) # 矩阵乘法

[[0 1]
 [2 3]]
[[10 10]
 [10 10]]
[[10 10]
 [50 50]]


In [78]:
print(a)
print(a.T) # 矩阵的转置

[[0 1]
 [2 3]]
[[0 2]
 [1 3]]


In [79]:
inv_a = np.linalg.inv(a)
print(a)
print(inv_a)

[[0 1]
 [2 3]]
[[-1.5  0.5]
 [ 1.   0. ]]


In [80]:
print(a.dot(inv_a)) # 原局长和逆矩阵矩阵乘法得到单位阵

[[1. 0.]
 [0. 1.]]


### 向量和矩阵间的运算

In [81]:
v = np.array([1, 2])
print(v)
print(a)
print(v + a)

[1 2]
[[0 1]
 [2 3]]
[[1 3]
 [3 5]]


### 聚合运算

In [82]:
big_array = np.random.random(1000000)
%time sum(big_array)
%time np.sum(big_array)

CPU times: user 36.1 ms, sys: 495 μs, total: 36.6 ms
Wall time: 36.7 ms
CPU times: user 151 μs, sys: 2 μs, total: 153 μs
Wall time: 153 μs


np.float64(499513.00105607137)

In [83]:
x = np.random.normal(0, 1, size=1000000)
print(f'min value index is {np.argmin(x)}') # 获得最小值位置索引
print(f'max value index is {np.argmax(x)}') # 获得最大值位置索引

min value index is 403567
max value index is 606328


### 数组排序

In [86]:
x = np.arange(16)
np.random.shuffle(x) # 将数组打乱
print(x)

z = np.sort(x) # 排序后返回新数组，x顺序不变
print(z)

print(np.argsort(x)) # 返回排序后数字的索引值，对矩阵同样成立

[ 3  2 13  9  5  0 15  8  6 14  4  1 12  7 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 5 11  1  0 10  4  8 13  7  3 14 15 12  2  9  6]


### 高级索引

In [87]:
x = np.arange(16)
print(x)

# 指定特定元素的索引
index = [3, 5, 8]
print(x[index])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[3 5 8]


In [88]:
# 根据原数组索引生成二维矩阵
index = np.array([[0, 2], [1, 3]])
print(x)
print(x[index])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[0 2]
 [1 3]]


In [89]:
w = x.reshape(4, -1)
print(w)

row = np.array([0, 1, 2])
col = np.array([1, 2, 3])
print(w[row, col])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[ 1  6 11]


In [90]:
print(w[0, col])
print(w[:2, col])

[1 2 3]
[[1 2 3]
 [5 6 7]]


In [91]:
col = [True, False, True, True]
print(w[1:3, col])

[[ 4  6  7]
 [ 8 10 11]]


### 布尔运算

In [92]:
x = np.arange(16)
print(x)
print(x < 3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ True  True  True False False False False False False False False False
 False False False False]


In [93]:
w = x.reshape(4, -1)
print(w)
print(w < 6)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ True  True  True  True]
 [ True  True False False]
 [False False False False]
 [False False False False]]


In [94]:
print(x)
print(np.sum(x <= 3))  # 统计小于3数据的数量

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
4


In [96]:
print(w)
print(np.sum((w > 3) & (w < 10))) # 与运算

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
6


In [97]:
print(x)
print(x[x < 5]) # 索引小于5的值

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[0 1 2 3 4]
