In [1]:
import numpy
numpy.__version__

'2.3.2'

In [2]:
l = [i for i in range(10)]
print(l)

l[5] = 100
print(l)

l[5] = 'learning numpy'
print(l)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 100, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 'learning numpy', 6, 7, 8, 9]


In [4]:
import array
arr = array.array('i', [i for i in range(10)])
print(arr)

arr[5] = 100
print(arr)

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
array('i', [0, 1, 2, 3, 4, 100, 6, 7, 8, 9])


In [5]:
arr[5] = 'learning numpy'

TypeError: 'str' object cannot be interpreted as an integer

In [6]:
import numpy as np

arr = np.array([i for i in range(10)])
print(arr)
print(type(arr))

arr[5] = 100
print(arr)

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
[  0   1   2   3   4 100   6   7   8   9]


In [7]:
arr[5] = 'learning numpy'

ValueError: invalid literal for int() with base 10: 'learning numpy'

In [8]:
print(arr.dtype)

int64


In [9]:
# 创建一个长度为10的数组，数组的值都是0。
zeros = np.zeros(10)
print(zeros)
print(zeros.dtype) # 默认的数量类型是浮点型。

zeros_two = np.zeros(10, dtype=int) # 创建整形数组。
print(zeros_two)
print(zeros_two.dtype)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
float64
[0 0 0 0 0 0 0 0 0 0]
int64


In [10]:
a = [1, 2, 3]
arr = np.zeros_like(a)
print(arr)

[0 0 0]


In [11]:
# 创建一个3×5的浮点型数组，数组的值都是1。
ones = np.ones(shape=(3, 5), dtype=float)
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [12]:
a = [[1, 2, 3], [4, 5, 6]]
arr = np.ones_like(a)
print(arr)

[[1 1 1]
 [1 1 1]]


In [13]:
# 创建一个3×5的浮点型数组，数组的值都是3.14。
w = np.full(shape=(3, 5), fill_value=3.14)
print(w)

[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]


In [14]:
arr = np.arange(0, 20, 2)
print(arr)

arr = np.arange(0, 1, 0.2) # arange支持浮点步长
print(arr)

arr = np.arange(0, 10) 
print(arr)
print(arr.dtype)

arr = np.arange(10)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]
[0.  0.2 0.4 0.6 0.8]
[0 1 2 3 4 5 6 7 8 9]
int64
[0 1 2 3 4 5 6 7 8 9]


In [15]:
arr = np.linspace(0, 20) 
print(arr)

arr = np.linspace(0, 20, 10)
print(arr)

arr = np.linspace(0, 20, 11)
print(arr)

[ 0.          0.40816327  0.81632653  1.2244898   1.63265306  2.04081633
  2.44897959  2.85714286  3.26530612  3.67346939  4.08163265  4.48979592
  4.89795918  5.30612245  5.71428571  6.12244898  6.53061224  6.93877551
  7.34693878  7.75510204  8.16326531  8.57142857  8.97959184  9.3877551
  9.79591837 10.20408163 10.6122449  11.02040816 11.42857143 11.83673469
 12.24489796 12.65306122 13.06122449 13.46938776 13.87755102 14.28571429
 14.69387755 15.10204082 15.51020408 15.91836735 16.32653061 16.73469388
 17.14285714 17.55102041 17.95918367 18.36734694 18.7755102  19.18367347
 19.59183673 20.        ]
[ 0.          2.22222222  4.44444444  6.66666667  8.88888889 11.11111111
 13.33333333 15.55555556 17.77777778 20.        ]
[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]


In [16]:
a = [[1, 2, 3], [4, 5, 6]]
a1 = np.array(a) # 深拷贝
print(a1)

a2 = np.asarray(a1) # 浅拷贝
print(a2)

a1[0][0] = 100
print(a)
print(a1)
print(a2)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1, 2, 3], [4, 5, 6]]
[[100   2   3]
 [  4   5   6]]
[[100   2   3]
 [  4   5   6]]


In [17]:
arr = np.random.randint(0, 10) # 生成一个随机整数，反正在[0, 10)之间
print(arr)

arr = np.random.randint(0, 10, 10) # 生成一维数组
print(arr)

arr = np.random.randint(0, 1, 10) # 测试随机数的范围
print(arr)

arr = np.random.randint(0, 10, size=10) # 显示指明数组大小
print(arr)

arr = np.random.randint(0, 10, size=(3, 5)) # 生成随机矩阵
print(arr)

7
[5 8 1 8 2 6 7 3 0 1]
[0 0 0 0 0 0 0 0 0 0]
[7 2 0 0 8 5 8 3 2 5]
[[5 4 4 7 0]
 [8 4 5 0 1]
 [2 0 9 8 2]]


In [18]:
np.random.seed(666)
arr = np.random.randint(4, 8, size=(3, 5))
print(arr)

[[4 6 5 6 6]
 [6 5 6 4 5]
 [7 6 7 4 7]]


In [19]:
arr = np.random.random(10)
print(arr)

arr = np.random.random((3, 5))
print(arr)

[0.28116849 0.46284169 0.23340091 0.76706421 0.81995656 0.39747625
 0.31644109 0.15551206 0.73460987 0.73159555]
[[0.8578588  0.76741234 0.95323137 0.29097383 0.84778197]
 [0.3497619  0.92389692 0.29489453 0.52438061 0.94253896]
 [0.07473949 0.27646251 0.4675855  0.31581532 0.39016259]]


In [20]:
value = np.random.normal()
print(value)

value = np.random.normal(10, 100)
print(value)

arr = np.random.normal(0, 1, (3, 5))
print(arr)

arr = np.random.normal(size=(3, 5))
print(arr)

0.9047266176428719
-72.62832650185376
[[ 0.82101369  0.36712592  1.65399586  0.13946473 -1.21715355]
 [-0.99494737 -1.56448586 -1.62879004  1.23174866 -0.91360034]
 [-0.27084407  1.42024914 -0.98226439  0.80976498  1.85205227]]
[[ 1.67819021 -0.98076924  0.47031082  0.18226991 -0.84388249]
 [ 0.20996833  0.22958666  0.26307642  2.16633222 -1.04887593]
 [-1.84768442  0.53401503 -1.19574802 -0.28915737 -0.24332703]]


In [21]:
arr = np.array([1, 2, 3, 4, 5, 6], dtype=np.float32)
print(arr)

[1. 2. 3. 4. 5. 6.]


In [22]:
arr = np.arange(10)
print(arr)
print(arr.dtype)

# 强制转换为整形
arr[5] = 3.14
print(arr)
print(arr.dtype)

# 创建浮点数据类型。
arr2 = np.array([1, 2, 3.14])
print(arr2.dtype)

[0 1 2 3 4 5 6 7 8 9]
int64
[0 1 2 3 4 3 6 7 8 9]
int64
float64


In [23]:
x = np.arange(15).reshape(3, 5)
y = np.arange(10)
print(x)
print(y)

# 数组的维度
print(x.ndim)
print(y.ndim)

# 数组的形状
print(x.shape)
print(y.shape)

# 数组中的元素数量
print(x.size)
print(y.size)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[0 1 2 3 4 5 6 7 8 9]
2
1
(3, 5)
(10,)
15
10


In [24]:
x = np.arange(10)
print(x.ndim)

w = x.reshape(2, 5)
print(w.ndim)

w = x.reshape(10, -1) # -1会根据数据数量和行数自动计算合适的列数。
print(w)

w = x.reshape(2, -1) 
print(w)

1
2
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [25]:
w = x.reshape(3, -1) 
print(x)

ValueError: cannot reshape array of size 10 into shape (3,newaxis)

In [28]:
x = np.arange(15).reshape(3, 5)
y = np.arange(10)
print(x)
print(y)

# 访问一维数组
print(y[0])
print(y[-1])

# 访问二维数组
print(x[2, 2]) # 使用元组访问，等价于x[(2, 2)]，推荐

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[0 1 2 3 4 5 6 7 8 9]
0
9
12


In [29]:
print(y[0:5])
print(y[:5])
print(y[5:])
print(y[::2])
print(y[::-1])

[0 1 2 3 4]
[0 1 2 3 4]
[5 6 7 8 9]
[0 2 4 6 8]
[9 8 7 6 5 4 3 2 1 0]


In [ ]:
print(x[:2, :3]) # 前两行前三列。
print(x[:2, ::2])

# 反转数组
print(x[::-1, ::-1])  

# 读取第一行
print(x[0])
print(x[0, :])

# 读取第一列
col = x[:, 0]
print(col.ndim)
print(col.shape)

[[0 1 2]
 [5 6 7]]
[[0 2 4]
 [5 7 9]]
[[14 13 12 11 10]
 [ 9  8  7  6  5]
 [ 4  3  2  1  0]]
[0 1 2 3 4]
[0 1 2 3 4]
1
(3,)


In [32]:
sub_x = x[:2, :3]
print(sub_x)
print(x)

sub_x[0, 0] = 100
print(sub_x)
print(x)

x[0, 0] = 0
print(x)
print(sub_x)

[[0 1 2]
 [5 6 7]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[100   1   2]
 [  5   6   7]]
[[100   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0 1 2]
 [5 6 7]]


In [ ]:
sub_x = x[:2, :3].copy()
sub_x[0, 0] = 100
print(sub_x)
print(x)

In [33]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
print(x)
print(y)
print(np.concatenate([x, y]))

a = np.array([[1, 2, 3], [4, 5, 6]])
print(np.concatenate([a, a]))  # 垂直方向进行拼接
print(np.concatenate([a, a], axis=1)) # 水平方向进行拼接


[1 2 3]
[3 2 1]
[1 2 3 3 2 1]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [34]:
np.concatenate([a, y]) # 向量和矩阵不能直接拼接
w = np.concatenate([a, y.reshape(1, -1)]) # 需要修改y的形状
print(w)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [35]:
w[0, 0] = 100
print(w)
print(x)

[[100   1   2   3   4]
 [  5   6   7   8   9]]
[1 2 3]


In [ ]:
print(np.vstack([a, y]))

b = np.full((2, 2), 100)
print(b)
print(np.hstack([a, b]))

[[1 2 3]
 [4 5 6]
 [3 2 1]]
[[100 100]
 [100 100]]
[[  1   2   3 100 100]
 [  4   5   6 100 100]]


In [38]:
print(np.hstack([a, y])) # 报错，数据在水平方向没有对齐。

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [40]:
x = np.arange(10)
x1, x2, x3 = np.split(x, [3, 7]) # 第二个参数为分割点，参数形式必须是数组。
print(x1, x2, x3)
w1, w2 = np.split(x, [5])
print(w1, w2)

[0 1 2] [3 4 5 6] [7 8 9]
[0 1 2 3 4] [5 6 7 8 9]


In [41]:
x1[0] = 100
print(x1)
print(x)

[100   1   2]
[100   1   2   3   4   5   6   7   8   9]


In [42]:
a = np.arange(16).reshape(4, 4)
a1, a2 = np.split(a, [2])  # 在水平方向上分割矩阵
print(a)
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [43]:
a1, a2, a3 = np.split(a, [2, 3], axis=1) # 在垂直方向上进行分割
print(a)
print(a1)
print(a2)
print(a3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2]
 [ 6]
 [10]
 [14]]
[[ 3]
 [ 7]
 [11]
 [15]]


In [45]:
upper, lower = np.vsplit(a, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [47]:
left, right = np.hsplit(a, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [48]:
# 获取最后一列，并转换为一维数组
x, y = np.hsplit(a, [-1])
y = y[:, 0] 
print(y)

[ 3  7 11 15]


In [49]:
n = 1000000
l = [i for i in range(n)]

In [50]:
%%time
double = []
for i in l:
    double.append(2 * i)
print(f"列表长度: {len(double)}")
print("前10个元素:", double[:10])

列表长度: 1000000
前10个元素: [0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
CPU times: user 29.2 ms, sys: 11.8 ms, total: 41.1 ms
Wall time: 48.3 ms


In [51]:
%%time
double = [2 * i for i in l]
print(f"列表长度: {len(double)}")
print("前10个元素:", double[:10])

列表长度: 1000000
前10个元素: [0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
CPU times: user 21.3 ms, sys: 11.7 ms, total: 33 ms
Wall time: 40.5 ms


In [52]:
l = np.arange(n)

In [53]:
%%time
double = np.array(2 * i for i in l)

CPU times: user 4.46 ms, sys: 2.25 ms, total: 6.71 ms
Wall time: 6.76 ms


In [54]:
%%time
double = 2 * l # Numpy支持向量与常数的运算操作
print(double)

[      0       2       4 ... 1999994 1999996 1999998]
CPU times: user 1.23 ms, sys: 1.62 ms, total: 2.85 ms
Wall time: 1.7 ms


In [55]:
x = np.arange(1, 16).reshape(3, 5)

print(x + 1)
print(x - 1)
print(x * 2)
print(x / 2)
print(x // 2)
print(x ** 2)
print(x % 2)
print(1 / x)

[[ 2  3  4  5  6]
 [ 7  8  9 10 11]
 [12 13 14 15 16]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]]
[[0.5 1.  1.5 2.  2.5]
 [3.  3.5 4.  4.5 5. ]
 [5.5 6.  6.5 7.  7.5]]
[[0 1 1 2 2]
 [3 3 4 4 5]
 [5 6 6 7 7]]
[[  1   4   9  16  25]
 [ 36  49  64  81 100]
 [121 144 169 196 225]]
[[1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]]
[[1.         0.5        0.33333333 0.25       0.2       ]
 [0.16666667 0.14285714 0.125      0.11111111 0.1       ]
 [0.09090909 0.08333333 0.07692308 0.07142857 0.06666667]]


In [56]:
print(np.abs(x))
print(np.sin(x))
print(np.cos(x))
print(np.tan(x))
print(np.exp(x))
print(np.power(3, x)) # 等价于x ** 3
print(np.log(x)) # 已e为底的对数
print(np.log2(x))
print(np.log10(x))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
 [-0.2794155   0.6569866   0.98935825  0.41211849 -0.54402111]
 [-0.99999021 -0.53657292  0.42016704  0.99060736  0.65028784]]
[[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
 [ 0.96017029  0.75390225 -0.14550003 -0.91113026 -0.83907153]
 [ 0.0044257   0.84385396  0.90744678  0.13673722 -0.75968791]]
[[ 1.55740772e+00 -2.18503986e+00 -1.42546543e-01  1.15782128e+00
  -3.38051501e+00]
 [-2.91006191e-01  8.71447983e-01 -6.79971146e+00 -4.52315659e-01
   6.48360827e-01]
 [-2.25950846e+02 -6.35859929e-01  4.63021133e-01  7.24460662e+00
  -8.55993401e-01]]
[[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
  1.48413159e+02]
 [4.03428793e+02 1.09663316e+03 2.98095799e+03 8.10308393e+03
  2.20264658e+04]
 [5.98741417e+04 1.62754791e+05 4.42413392e+05 1.20260428e+06
  3.26901737e+06]]
[[       3        9       27       81      243]
 [     729     2187 

In [57]:
a = np.arange(4).reshape(2, 2)
b = np.full((2, 2), 10)

print(a + b)
print(a - b)
print(a * b)
print(a / b)

[[10 11]
 [12 13]]
[[-10  -9]
 [ -8  -7]]
[[ 0 10]
 [20 30]]
[[0.  0.1]
 [0.2 0.3]]


In [58]:
print(a.dot(b)) # 矩阵乘法
print(a.T) # 矩阵的转置

[[10 10]
 [50 50]]
[[0 2]
 [1 3]]


In [59]:
inv_a = np.linalg.inv(a)

print(a.dot(inv_a)) # 原局长和逆矩阵矩阵乘法得到单位阵
print(inv_a.dot(a))

[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]


In [60]:
v = np.array([1, 2])
print(v + a)
print(v * a)

[[1 3]
 [3 5]]
[[0 2]
 [2 6]]


In [61]:
print(np.tile(v, (2, 1))) # 水平方向上堆叠2次，垂直方向闪堆叠1次。
print(np.tile(v, (2, 2)))

print(np.tile(v, (2, 1)) + a) # 与v+a操作相同

[[1 2]
 [1 2]]
[[1 2 1 2]
 [1 2 1 2]]
[[1 3]
 [3 5]]


In [62]:
print(v.dot(a))
print(a.dot(v)) # Numpy可以自动转换向量形式与矩阵进行运算

[4 7]
[2 8]


In [63]:
big_array = np.random.random(1000000)
%time sum(big_array)
%time np.sum(big_array)

CPU times: user 35.2 ms, sys: 5.22 ms, total: 40.4 ms
Wall time: 49.9 ms
CPU times: user 291 μs, sys: 71 μs, total: 362 μs
Wall time: 259 μs


np.float64(500179.6546187949)

In [64]:
print(np.min(big_array))
np.max(big_array)

# 部分聚合操作可以通过向量直接调用
print(big_array.min())
print(big_array.max())
print(big_array.sum())

# 聚合运算默认是对整个数组进行计算
x = np.arange(16).reshape(4, 4)
print(np.sum(x))

# 指定方向的求和
print(np.sum(x, axis=0)) # 在水平方向进行压缩
print(np.sum(x, axis=1)) # 在垂直方向进行压缩，计算结果仍未一维向量。

1.827632976070248e-06
1.827632976070248e-06
0.9999993748010294
500179.6546187949
120
[24 28 32 36]
[ 6 22 38 54]


In [65]:
print(np.prod(x+1)) # 将所有数相乘
print(np.mean(x)) # 求均值
print(np.median(x)) # 求中位数
print(np.var(big_array)) # 求方差
print(np.std(big_array)) # 求标准差

20922789888000
7.5
7.5
0.08341548789604251
0.28881739541800894


In [66]:
x = np.random.normal(0, 1, size=1000000)
print(np.argmin(x)) # 获得最小值位置索引
print(np.argmax(x)) # 获得最大值位置索引

610335
849856


In [67]:
x = np.arange(16)
np.random.shuffle(x) # 将数组打乱
print(x)

z = np.sort(x) # 排序后返回新数组，x顺序不变
print(z)

x.sort() # 对x自身排序
print(x)

[ 5 12 10  7  9 15 14  8  2 13  4 11  0  1  3  6]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [68]:
x = np.random.randint(10, size=(4, 4))

print(np.sort(x)) # 对每一行数据进行排序
print(np.sort(x, axis=0)) # 沿着水平方向进行排序

[[2 2 5 8]
 [2 4 5 8]
 [1 4 8 9]
 [0 1 3 6]]
[[2 0 1 4]
 [3 2 1 6]
 [5 4 2 8]
 [9 8 5 8]]


In [69]:
x = np.arange(16)
np.random.shuffle(x)
print(x)

print(np.argsort(x)) # 返回排序后数字的索引值，对矩阵同样成立

[ 4 10  9  5 13  2 14  0  3 15  8 11 12  7  1  6]
[ 7 14  5  8  0  3 15 13 10  2  1 11 12  4  6  9]


In [71]:
x = np.arange(16)
print(x)

# 指定特定元素的索引
index = [3, 5, 8]
print(x[index])

# 根据原数组索引生成二维矩阵
index = np.array([[0, 2], [1, 3]])
print(x[index])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[3 5 8]
[[0 2]
 [1 3]]


In [72]:
w = x.reshape(4, -1)
print(w)

row = np.array([0, 1, 2])
col = np.array([1, 2, 3])
print(w[row, col])
print(w[0, col])
print(w[:2, col])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[ 1  6 11]
[1 2 3]
[[1 2 3]
 [5 6 7]]


In [73]:
col = [True, False, True, True]
print(w[1:3, col])

[[ 4  6  7]
 [ 8 10 11]]


In [74]:
x = np.arange(16)
print(x)

print(x < 3)
print(x > 3)
print(x <= 3)
print(x >= 3)
print(x == 3)
print(x != 3)

w = x.reshape(4, -1)
print(w < 6)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ True  True  True False False False False False False False False False
 False False False False]
[False False False False  True  True  True  True  True  True  True  True
  True  True  True  True]
[ True  True  True  True False False False False False False False False
 False False False False]
[False False False  True  True  True  True  True  True  True  True  True
  True  True  True  True]
[False False False  True False False False False False False False False
 False False False False]
[ True  True  True False  True  True  True  True  True  True  True  True
  True  True  True  True]
[[ True  True  True  True]
 [ True  True False False]
 [False False False False]
 [False False False False]]


In [75]:
print(np.sum(x <= 3))  # 统计小于3数据的数量
print(np.count_nonzero(x <= 3))  # 统计0元素

4
4


In [76]:
print(np.any(x == 0)) # 是否存等于0的元素
print(np.any(x < 0)) # 是否存在小于0的元素

True
False


In [77]:
print(np.all(x >= 0)) # 全部元素都大于等于0
print(np.all(x > 0)) # 全部元素大于0

True
False


In [78]:
print(np.sum(w % 2 == 0)) # 判断矩阵中有多少偶数
print(np.sum(w % 2 == 0, axis=1)) # 计算每一列有多少偶数
print(np.all(w > 0, axis=1)) # 判断在列方向上是否全部大于0

8
[2 2 2 2]
[False  True  True  True]


In [79]:
print(np.sum((w > 3) & (w < 10))) # 与运算
print(np.sum((w % 2 == 0) | (w > 10))) # 或运算
print(np.sum(~(w == 0))) # 非运算

6
11
15


In [80]:
print(x[x < 5]) # 索引小于5的值
print(x[x % 2 == 0]) # 所有的偶数值
print(w[w[:, 3] % 3 == 0, :]) # w最后一列可以被3整除的行构成的数组。

[0 1 2 3 4]
[ 0  2  4  6  8 10 12 14]
[[ 0  1  2  3]
 [12 13 14 15]]
